import type { UserProfile } from "@/context/AuthContext"

export const sampleUserProfiles: Record<string, UserProfile> = {
  "user-elara": {
    uid: "user-elara",
    name: "Elara Vance",
    email: "elara@example.com",
    title: "AI Project Lead & Innovator",
    avatarUrl: "/placeholder.svg?height=128&width=128",
    avatarFallback: "EV",
    bio: "Leading the charge in AI-driven project management. Passionate about SaaS and product development. Looking for collaborators on TaskFlow AI!",
    skills: ["AI", "SaaS", "Product Management", "Leadership", "Next.js"],
    interests: ["Machine Learning", "Startups", "Agile Development", "UX Design"],
    linkedinUrl: "https://linkedin.com/in/elaravance",
    githubUrl: "https://github.com/elaravance",
    twitterUrl: "https://x.com/elaravance",
    instagramUrl: "https://instagram.com/elaravance",
  },
  "user-marcus": {
    uid: "user-marcus",
    name: "Marcus Chen",
    email: "marcus@example.com",
    title: "Eco-Tech Entrepreneur & Founder of EcoWidgets",
    avatarUrl: "/placeholder.svg?height=128&width=128",
    avatarFallback: "MC",
    bio: "Building sustainable alternatives for everyday tech. Recently secured pre-seed funding for EcoWidgets and seeking talent!",
    skills: ["Sustainability", "Hardware Development", "Business Strategy", "Fundraising", "Circular Economy"],
    interests: ["Green Tech", "Impact Investing", "Renewable Energy"],
    linkedinUrl: "https://linkedin.com/in/marcuschen",
  },
  "user-sophia": {
    uid: "user-sophia",
    name: "Sophia Al-Jamil",
    email: "sophia@example.com",
    title: "Fintech Innovator & UX Strategist",
    avatarUrl: "/placeholder.svg?height=128&width=128",
    avatarFallback: "SA",
    bio: "Disrupting the payment platform space with a focus on user experience. Hiring UX/UI designers with fintech experience - join my new venture!",
    skills: ["Fintech", "UX/UI Strategy", "Team Building", "Payments", "Product Design"],
    interests: ["Blockchain", "User-Centered Design", "Financial Inclusion", "Mobile Payments"],
    githubUrl: "https://github.com/sophiaaljamil",
  },
  "demo-user-123": {
    uid: "demo-user-123",
    name: "Demo User",
    email: "demo@startlinker.com",
    title: "Entrepreneur",
    avatarUrl: "/placeholder.svg?height=128&width=128",
    avatarFallback: "DU",
    bio: "Welcome to StartLinker! This is a demo account to explore the platform.",
    skills: ["React", "TypeScript", "Entrepreneurship"],
    interests: ["Startups", "Technology", "Innovation"],
  },
}
